server:
	gcc -o client1 tcpclient.c
	gcc -o	client2 tcpclient.c
	gcc -o	client3 tcpclient.c
	gcc -o	client4 tcpclient.c
	gcc -o	client5 tcpclient.c
	gcc -o server tcpserver.c
	rm -f client1 client2 client3 client4 client5 server
	./server 

