all:
	gcc -o server server.c
	gcc -o client1 client1.c
	gcc -o client2 client2.c
	gcc -o client3 client3.c
	gcc -o client4 client4.c
	./server tasks.txt

clean:
	rm -f server client1 client2 client3 client4
